const products = [
    {
      id: 1,
      name: "iPhone 13",
      brand: "Apple",
      price: 999,
      category: "phones",
      description: "The iPhone 13 offers an advanced A15 Bionic chip and a ProMotion display.",
      ratings: 4.8,
      stock: 200,
      reviews: 20,
      image: "images/iphone13.jpg"
    },
    {
      id: 2,
      name: "Galaxy S22",
      brand: "Samsung",
      price: 899,
      category: "phones",
      description: "The Galaxy S22 boasts a stunning Dynamic AMOLED 2X display and an Exynos 990 processor.",
      ratings: 4.6,
      stock: 150,
      reviews: 15,
      image: "images/galaxys22.jpg"
    },
    {
      id: 3,
      name: "Pixel 6",
      brand: "Google",
      price: 799,
      category: "phones",
      description: "The Pixel 6 features a powerful Google Tensor chip and an impressive camera system.",
      ratings: 4.7,
      stock: 180,
      reviews: 18,
      image: "images/pixel6.jpg"
    },
    {
      id: 4,
      name: "OnePlus 9 Pro",
      brand: "OnePlus",
      price: 899,
      category: "phones",
      description: "The OnePlus 9 Pro offers a fluid AMOLED display and Warp Charge 65T fast charging.",
      ratings: 4.5,
      stock: 220,
      reviews: 21,
      image: "images/oneplus9pro.jpg"
    },
    {
      id: 5,
      name: "Mi 12",
      brand: "Xiaomi",
      price: 699,
      category: "phones",
      description: "The Mi 12 features a Snapdragon 895 processor and a high-refresh-rate AMOLED display.",
      ratings: 4.4,
      stock: 190,
      reviews: 19,
      image: "images/mi12.jpg"
    },
    {
      id: 6,
      name: "MacBook Air M1",
      brand: "Apple",
      price: 999,
      category: "laptops",
      description: "The MacBook Air M1 delivers powerful performance with its Apple M1 chip and a stunning Retina display.",
      ratings: 4.9,
      stock: 80,
      reviews: 25,
      image: "images/macbookairm1.jpg"
    },
    {
      id: 7,
      name: "XPS 15",
      brand: "Dell",
      price: 1899,
      category: "laptops",
      description: "The XPS 15 offers a breathtaking 4K UHD display and a powerful Intel Core i7 processor.",
      ratings: 4.7,
      stock: 100,
      reviews: 12,
      image: "images/xps15.jpg"
    },
    {
      id: 8,
      name: "ThinkPad X1 Carbon",
      brand: "Lenovo",
      price: 1599,
      category: "laptops",
      description: "The ThinkPad X1 Carbon combines durability, performance, and a stunning 4K Dolby Vision display.",
      ratings: 4.8,
      stock: 90,
      reviews: 14,
      image: "images/thinkpadx1carbon.jpg"
    },
    {
      id: 9,
      name: "Surface Laptop 4",
      brand: "Microsoft",
      price: 1399,
      category: "laptops",
      description: "The Surface Laptop 4 offers a touchscreen display and all-day battery life for maximum productivity.",
      ratings: 4.6,
      stock: 120,
      reviews: 16,
      image: "images/surfacelaptop4.jpg"
    },
    {
      id: 10,
      name: "ROG Zephyrus G14",
      brand: "ASUS",
      price: 1499,
      category: "laptops",
      description: "The ROG Zephyrus G14 packs powerful gaming performance into a compact and lightweight design.",
      ratings: 4.7,
      stock: 110,
      reviews: 13,
      image: "images/rogzephyrusg14.jpg"
    },
    {
      id: 11,
      name: "AirPods Max",
      brand: "Apple",
      price: 549,
      category: "phone accessories",
      description: "AirPods Max deliver high-fidelity audio and a luxurious over-ear design with active noise cancellation.",
      ratings: 4.8,
      stock: 300,
      reviews: 28,
      image: "images/airpodsmax.jpg"
    },
    {
      id: 12,
      name: "Galaxy Buds Pro",
      brand: "Samsung",
      price: 199,
      category: "phone accessories",
      description: "Galaxy Buds Pro provide immersive sound, intelligent ANC, and seamless integration with Samsung devices.",
      ratings: 4.6,
      stock: 250,
      reviews: 26,
      image: "images/galaxybudspro.jpg"
    },
    {
      id: 13,
      name: "Powerbeats Pro",
      brand: "Beats",
      price: 249,
      category: "phone accessories",
      description: "Powerbeats Pro offer powerful, balanced sound and adjustable ear hooks for a secure fit during workouts.",
      ratings: 4.7,
      stock: 180,
      reviews: 20,
      image: "images/powerbeatspro.jpg"
    },
    {
      id: 14,
      name: "Wireless Charger",
      brand: "Anker",
      price: 29,
      category: "phone accessories",
      description: "This wireless charger supports fast charging and features a compact design for easy portability.",
      ratings: 4.5,
      stock: 500,
      reviews: 29,
      image: "images/wirelesscharger.jpg"
    },
    {
      id: 15,
      name: "Phone Tripod",
      brand: "Joby",
      price: 39,
      category: "phone accessories",
      description: "The Joby phone tripod provides stability and flexibility for capturing photos and videos on the go.",
      ratings: 4.3,
      stock: 400,
      reviews: 18,
      image: "images/phonetripod.jpg"
    },
    {
      id: 16,
      name: "Nest Learning Thermostat",
      brand: "Google",
      price: 249,
      category: "smart devices",
      description: "The Nest Learning Thermostat programs itself and helps save energy with its smart features.",
      ratings: 4.7,
      stock: 150,
      reviews: 17,
      image: "images/nestlearningthermostat.jpg"
    },
    {
      id: 17,
      name: "Echo Dot (4th Gen)",
      brand: "Amazon",
      price: 49,
      category: "smart devices",
      description: "The Echo Dot is a compact smart speaker that delivers rich sound and integrates with Alexa.",
      ratings: 4.6,
      stock: 200,
      reviews: 23,
      image: "images/echodot.jpg"
    },
    {
      id: 18,
      name: "HomePod mini",
      brand: "Apple",
      price: 99,
      category: "smart devices",
      description: "The HomePod mini offers high-quality sound and Siri intelligence in a small, smart speaker.",
      ratings: 4.8,
      stock: 180,
      reviews: 21,
      image: "images/homepodmini.jpg"
    },
    {
      id: 19,
      name: "Wyze Cam v3",
      brand: "Wyze",
      price: 29,
      category: "smart devices",
      description: "The Wyze Cam v3 is a feature-rich security camera with night vision and two-way audio.",
      ratings: 4.4,
      stock: 250,
      reviews: 16,
      image: "images/wyzecamv3.jpg"
    },
    {
      id: 20,
      name: "August Smart Lock Pro",
      brand: "August",
      price: 199,
      category: "smart devices",
      description: "The August Smart Lock Pro provides secure, keyless access and works with popular smart home platforms.",
      ratings: 4.5,
      stock: 220,
      reviews: 19,
      image: "images/augustsmartlockpro.jpg"
    },
    {
      id: 21,
      name: "Zenfone 8",
      brand: "ASUS",
      price: 699,
      category: "phones",
      description: "The Zenfone 8 features a compact design, a Snapdragon 888 processor, and a high-refresh-rate AMOLED display.",
      ratings: 4.7,
      stock: 180,
      reviews: 17,
      image: "images/zenfone8.jpg"
    },
    {
      id: 22,
      name: "Surface Book 4",
      brand: "Microsoft",
      price: 1999,
      category: "laptops",
      description: "The Surface Book 4 offers a detachable display and powerful performance for creative professionals.",
      ratings: 4.9,
      stock: 90,
      reviews: 11,
      image: "images/surfacebook4.jpg"
    },
    {
      id: 23,
      name: "AirPods 3",
      brand: "Apple",
      price: 179,
      category: "phone accessories",
      description: "AirPods 3 feature a new design, improved sound quality, and seamless integration with Apple devices.",
      ratings: 4.6,
      stock: 300,
      reviews: 22,
      image: "images/airpods3.jpg"
    },
    {
      id: 24,
      name: "Galaxy Watch 4",
      brand: "Samsung",
      price: 299,
      category: "phone accessories",
      description: "The Galaxy Watch 4 offers advanced health and fitness tracking features in a stylish design.",
      ratings: 4.7,
      stock: 250,
      reviews: 24,
      image: "images/galaxywatch4.jpg"
    },
    {
      id: 25,
      name: "Google Nest Hub (2nd Gen)",
      brand: "Google",
      price: 99,
      category: "smart devices",
      description: "The Google Nest Hub (2nd Gen) provides a smart display and serves as a central hub for your smart home.",
      ratings: 4.8,
      stock: 200,
      reviews: 26,
      image: "images/nesthub.jpg"
    },
    {
      id: 26,
      name: "Ring Video Doorbell Pro",
      brand: "Ring",
      price: 249,
      category: "smart devices",
      description: "The Ring Video Doorbell Pro offers advanced motion detection and 1080p HD video recording.",
      ratings: 4.6,
      stock: 150,
      reviews: 20,
      image: "images/ringvideodoorbellpro.png"
    },
    {
      id: 27,
      name: "Redmi Note 11 Pro",
      brand: "Xiaomi",
      price: 349,
      category: "phones",
      description: "The Redmi Note 11 Pro features a high-resolution display, a powerful MediaTek Dimensity processor, and a large battery.",
      ratings: 4.5,
      stock: 220,
      reviews: 18,
      image: "images/redminote11pro.jpg"
    },
    {
      id: 28,
      name: "Razer Blade 15",
      brand: "Razer",
      price: 1999,
      category: "laptops",
      description: "The Razer Blade 15 offers top-tier gaming performance and a sleek design with customizable RGB lighting.",
      ratings: 4.7,
      stock: 180,
      reviews: 15,
      image: "images/razerblade15.jpg"
    },
    {
      id: 29,
      name: "Wireless Earbuds",
      brand: "Sony",
      price: 199,
      category: "phone accessories",
      description: "These Sony wireless earbuds feature noise cancellation and high-quality audio for an immersive listening experience.",
      ratings: 4.4,
      stock: 250,
      reviews: 19,
      image: "images/wirelessearbuds.jpg"
    },
    {
      id: 30,
      name: "Google Nest Cam Indoor",
      brand: "Google",
      price: 179,
      category: "smart devices",
      description: "The Google Nest Cam Indoor offers 24/7 live streaming and advanced motion detection for home security.",
      ratings: 4.5,
      stock: 200,
      reviews: 22,
      image: "images/nestcamindoor.jpg"
    },
  ];